name: Deploy

on:
  workflow_run:
    workflows:
      - Validate
    types:
      - completed
    branches:
      - main

concurrency:
  group: pages-deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: deploy
    if: github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.event == 'push' || github.event.workflow_run.event == 'workflow_dispatch')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
      - run: yarn install --immutable
      - name: Build
        run: NUXT_APP_BASE_URL=/subscript-editor/ yarn build --preset 'github-pages'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
