name: Validate

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: validate-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    environment: validation
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
      - run: yarn install --immutable
      - name: Typecheck
        run: yarn typecheck
      - name: Lint
        run: yarn lint:check
      - name: Build
        run: NUXT_APP_BASE_URL=/subscript-editor/ yarn build --preset 'github-pages'
